import type { Metadata } from "next";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { LocaleProvider } from "@/context/LocaleContext";
import NavBar from "@/components/NavBar/NavBar";
import Footer from "@/components/Footer/Footer";
import "@/styles/globals.scss";

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export const metadata: Metadata = {
  title: "Auralis",
  description: "Generated by Gianni",
};

export default async function LocaleLayout({ children, params }: Props) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  let messages;

  try {
    const navbar = (await import(`../../../messages/${locale}/navbar.json`))
      .default;
    const home = (await import(`../../../messages/${locale}/home.json`))
      .default;
    const about = (await import(`../../../messages/${locale}/about.json`))
      .default;
    const workflow = (await import(`../../../messages/${locale}/workflow.json`))
      .default;
    const services = (await import(`../../../messages/${locale}/services.json`))
      .default;
    const artworks = (await import(`../../../messages/${locale}/artworks.json`))
      .default;
    const contactForm = (
      await import(`../../../messages/${locale}/contactForm.json`)
    ).default;
    const faqs = (await import(`../../../messages/${locale}/faqs.json`))
      .default;
    const footer = (await import(`../../../messages/${locale}/footer.json`))
      .default;

    messages = {
      Navbar: navbar,
      Home: home,
      About: about,
      Workflow: workflow,
      Services: services,
      Artworks: artworks,
      ContactForm: contactForm,
      Faqs: faqs,
      Footer: footer,
    };
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
  } catch (error) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body>
        <LocaleProvider>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <NavBar />
            {children}
            <Footer />
          </NextIntlClientProvider>
        </LocaleProvider>
      </body>
    </html>
  );
}
